### ISSUE TITLE
Create a tag for this project

### ISSUE THREAD

**Issue by jose-oliveira** [cweagans/php-webdam-client#13]
Given that this project doesn't have tags, we must require the master branch as a dependency which causes the repo to be cloned and we got reports of issues because of that. Could you please push a tag so we can refer to it instead?

**Comment by cweagans** [comment]
Done! https://github.com/cweagans/php-webdam-client/releases/tag/1.0.0

I also added you and @nerdstein as maintainers, so feel free to go to town. Down the road, if you'd like to move this repo to the Acquia org, I'm totally fine with it. I don't have a webdam account anymore, so it doesn't make much sense for me to be maintaining this going forward.

**Comment by jose-oliveira** [comment]
Thanks for the quick response!
